import hashlib
import json
from typing import Optional

try:
    from .contract_interface import log_report
    BLOCKCHAIN_AVAILABLE = True
except (ImportError, EnvironmentError):
    print("⚠️  Blockchain interface not available. Logging disabled.")
    BLOCKCHAIN_AVAILABLE = False

def generate_hash(data: dict) -> str:
    """Generates SHA256 hash of the report data.
    Returns a hex string prefixed with 0x.
    """
    # Create a copy to avoid modifying the original
    data_copy = data.copy()
    
    # Remove dynamic fields that shouldn't be part of the immutable hash
    # e.g., id (if generated by DB), created_at, etc. if they vary
    # For now, we hash whatever is passed, assuming it's the canonical report data
    
    serialized = json.dumps(data_copy, sort_keys=True).encode('utf-8')
    hash_hex = hashlib.sha256(serialized).hexdigest()
    return f"0x{hash_hex}"

def write_hash_to_chain(report_hash: str) -> Optional[str]:
    """Writes the report hash to the blockchain.
    Returns the transaction hash as a hex string.
    """
    if not BLOCKCHAIN_AVAILABLE:
        return None

    try:
        report_id, tx_hash = log_report(report_hash)
        print(f"✅ Report logged to blockchain. ID: {report_id}, Tx: {tx_hash}")
        return tx_hash
        
    except Exception as e:
        print(f"❌ Blockchain error: {e}")
        return None
